script: util/travis.sh
after_success: util/travis_success.sh
branches:
  only:
    - master
notifications:
  recipients:
    - axr-ci@googlegroups.com
  email:
    on_success: change
    on_failure: always
