script: util/travis.sh
branches:
  only:
    - master
notifications:
  recipients:
    - axr-ci@googlegroups.com
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://deploy.axrproject.org/data.php
    on_success: always
    on_failure: never
    on_start: false
